DEBUG: false

db_filename: ./nostr.sqlite3

relay_name: python relay
relay_description: relay written in python
sysop_pubkey: 
sysop_contact: 
# options are disabled, passive, enabled
nip05_verification: disabled
verification_expiration: 86400 * 30
verification_update_frequency: 3600
#verification_blacklist:
# - badhost.biz
#verification_whitelist:
# - goodhost.com


gunicorn:
  bind: 127.0.0.1:6969
  workers: 1
  loglevel: info
  reload: false
