DEBUG: false

relay_name: python relay
relay_description: relay written in python
sysop_pubkey: 
sysop_contact: 

storage:
  sqlalchemy.url: sqlite+aiosqlite:///nostr.sqlite3
  # the number of concurrent REQ queries sent to the db
  num_concurrent_reqs: 10
  # the number of concurrent event saves. (sqlite can only support 1 writer at a time)
  num_concurrent_adds: 2
  validators:
    - nostr_relay.validators.is_not_too_large
    - nostr_relay.validators.is_signed
    - nostr_relay.validators.is_recent

verification:
  # options are disabled, passive, enabled
  nip05_verification: disabled
  expiration: 86400 * 30
  update_frequency: 3600
  #blacklist:
  # - badhost.biz
  #whitelist:
  # - goodhost.com


gunicorn:
  bind: 127.0.0.1:6969
  workers: 1
  loglevel: info
  reload: false


# see docs/authentication.md
authentication:
  enabled: false
  valid_urls: 
    - ws://localhost:6969
    - ws://127.0.0.1:6969
  actions:
    save: a
    query: a

# number of seconds to allow between client messages
message_timeout: 1800

# number of open subscriptions per connection
subscription_limit: 32

# set this to a private key used for internal control events
# service_privatekey: 9627da965699a2a3048f97b77df5047e8cd0d11daca75e7687d0b28b65416a3c

# set this to limit the number of events returned per REQ
max_limit: 6000
